### ISSUE TITLE
使用vite时，菜单栏图标无法显示，悬浮侧边栏样式有问题

### ISSUE THREAD

**Issue by Mikasa33** [vueComponent/pro-layout#107]
菜单栏图标无法显示，控制台警告：
![image](https://user-images.githubusercontent.com/29498153/111264956-5c19a180-8663-11eb-92b6-873a080de562.png)

悬浮侧边栏样式被覆盖问题：
![image](https://user-images.githubusercontent.com/29498153/111265047-7d7a8d80-8663-11eb-9e23-1b9aa37cb85e.png)
![image](https://user-images.githubusercontent.com/29498153/111265094-8d926d00-8663-11eb-9f66-012dadb5ea12.png)

**Comment by sendya** [comment]
测试过没问题，可能你需要配一下 optimizeDeps 的 ant-design/icons-vue

**Comment by Mikasa33** [comment]
样式问题看这里
https://github.com/vueComponent/pro-layout/issues/114#issuecomment-807909585

```
// 在 main.js 最顶部引入就好了
import 'ant-design-vue/dist/antd.less'
// ......
```
