### ISSUE TITLE
prolayout组件属性onOpenKeys:(openKeys: string[]) => {}，ts类型检查报错

### ISSUE THREAD

**Issue by xwnwho** [vueComponent/pro-layout#111]
version:  next
error: 不能将类型“(openKeys: string[]) => void”分配给类型“((openKeys: WithFalse<string[]>) => void) & ((openKeys: WithFalse<string[]>) => void)”。
像是onOpenKeys和onSelect函数的入参应该都是string[]类型吧，不应该会有false类型

**Comment by sendya** [comment]
可以关闭 selectedKeys 和 openKeys 所以肯定有 false 类型

**Comment by sendya** [comment]
openKeys: string[] | false 
selectedKeys: string[] | false
