### ISSUE TITLE
菜单无法展开问题

### ISSUE THREAD

**Issue by rosealba** [vueComponent/pro-layout#116]
bate.5  无法展开菜单，菜单收缩点击也无效 
![image](https://user-images.githubusercontent.com/37865704/114367520-18a54b00-9baf-11eb-8d7e-9a37f459da2c.png)
![image](https://user-images.githubusercontent.com/37865704/114367671-3d99be00-9baf-11eb-87bc-0b0ca333fce0.png)
![image](https://user-images.githubusercontent.com/37865704/114367731-51452480-9baf-11eb-923f-59e4c6fdfc9c.png)

**Comment by rosealba** [comment]
不知道是不是版本冲突

**Comment by sendya** [comment]
@open-keys, @selected-keys 事件没绑定
