### ISSUE TITLE
使用cdn会使导航菜单在isMobile=true时无法渲染

### ISSUE THREAD

**Issue by zhangmrit** [vueComponent/pro-layout#12]

**Comment by zhangmrit** [comment]
别的不用，就设置antdv 为cdn引用就会复现，使用的是 https://cdn.jsdelivr.net/npm/ant-design-vue@1.6.0/dist/antd-with-locales.js

**Comment by zhangmrit** [comment]
pro-layout中antdv的版本是1.5.3 因此触发的问题

**Comment by sendya** [comment]
@ant-design-vue/pro-layout@0.3.2
