### ISSUE TITLE
version: 3.0.0-beta.6, 引用ant-design-vue/es/style/themes/default.less的路径报错

### ISSUE THREAD

**Issue by xwnwho** [vueComponent/pro-layout#121]
@import 'ant-design-vue/es/style/themes/default.less';
目前npm的最新版本

**Comment by sendya** [comment]
报什么错？

**Comment by sendya** [comment]
可以先检查一下是不是 less4，不是就需要升级到 less4

**Comment by ajiebp1977** [comment]
less 和less-loader对应的版本:
    "less": "^4.1.1",
    "less-loader": "^7.3.0",

还要修改vue.config.js 的css部分为：

  css: {
    sourceMap: false,
    loaderOptions: {
      less: {
        lessOptions: {
          javascriptEnabled: true,
          modifyVars: {
            'border-radius-base': '2px',
          },
        },
      },
    },
  },

这么处理后，这个问题解决。

**Comment by xwnwho** [comment]
> less 和less-loader对应的版本:
> "less": "^4.1.1",
> "less-loader": "^7.3.0",
> 
> 还要修改vue.config.js 的css部分为：
> 
> css: {
> sourceMap: false,
> loaderOptions: {
> less: {
> lessOptions: {
> javascriptEnabled: true,
> modifyVars: {
> 'border-radius-base': '2px',
> },
> },
> },
> },
> },
> 
> 这么处理后，这个问题解决。

解决了，多谢。
