### ISSUE TITLE
openKeys 默认展开菜单 1.0.8版本一下

### ISSUE THREAD

**Issue by asukicany** [vueComponent/pro-layout#123]
version：1.0.8
vue-antd-pro

  <pro-layout
    :menus="menus"
    :collapsed="collapsed"
    :mediaQuery="query"
    :isMobile="isMobile"
    :handleMediaQuery="handleMediaQuery"
    :handleCollapse="handleCollapse"
    :i18nRender="i18nRender"
    v-bind="settings"
  
  >
怎么添加openKeys，在readme中没有看到相关的api说明，1.0.8没有这个吗？

**Comment by asukicany** [comment]
@sendya

**Comment by sendya** [comment]
没有，1x 版本不打算提供
