### ISSUE TITLE
如何 去掉或者隐藏 logo 的链接   还有 mobile模式下的点击菜单后  自动隐藏菜单

### ISSUE THREAD

**Issue by shizetao** [vueComponent/pro-layout#127]

**Comment by xwnwho** [comment]
menuHeaderRender配置可以自定义的，[示例](https://github.com/vueComponent/pro-layout/blob/next/examples/index.tsx)

 onSelect，点击菜单之后的回调函数

**Comment by shizetao** [comment]
> menuHeaderRender配置可以自定义的，[示例](https://github.com/vueComponent/pro-layout/blob/next/examples/index.tsx)
> 
> onSelect，点击菜单之后的回调函数

好的  我试一试  谢谢大佬

**Comment by gaopeak** [comment]
为什么例子都打不开了
