### ISSUE TITLE
路由设置target为_blank时控制台会给一个警告

### ISSUE THREAD

**Issue by Fallsleep** [vueComponent/pro-layout#129]
目前升级到`3.0.0-beta.11`，使用的vite作为构建工具，使用时产生这样的一个警告：
```
 [Vue warn]: Failed to resolve component: a 
```
代码在[BaseMenu.tsx 196行](https://github.com/vueComponent/pro-layout/blob/1c2a611c430bf030a369fe2ea6bf46f4e1a59dd9/src/SiderMenu/BaseMenu.tsx#L196)
```typescript
    const CustomTag: any = resolveComponent((target && 'a') || 'router-link');
```
虽然页面中正常显示了`a`标签，但不知道实际上是否有问题。

**Comment by Fallsleep** [comment]
另外`getMenuData`方法调用的[formatRelativePath](https://github.com/vueComponent/pro-layout/blob/1c2a611c430bf030a369fe2ea6bf46f4e1a59dd9/src/utils/getMenuData.ts#L8)方法会把`http(s)://`开头的菜单地址改成`/http(s):/`，和`1.x`早期版本的存在一样的问题

**Comment by sendya** [comment]
来个 PR?

**Comment by Fallsleep** [comment]
@sendya 发版到npm上的是v3分支？我去现学一下怎么PR，另外多集成一些内容到原来的旧框架里再一起PR吧

**Comment by sendya** [comment]
升级最新版
