### ISSUE TITLE
pro-layout菜单项的title不显示

### ISSUE THREAD

**Issue by yxdy1990** [vueComponent/pro-layout#13]
求助：menus中的数据都正常，但是界面渲染出来后，meta中的title不显示。

**Comment by sendya** [comment]
代码呢？

**Comment by yxdy1990** [comment]
<template>
  <pro-layout
    title="xxxxxx"
    :menus="menus"
    :collapsed="collapsed"
    :mediaQuery="query"
    :isMobile="isMobile"
    :handleMediaQuery="handleMediaQuery"
    :handleCollapse="handleCollapse"
    :logo="logoRender"
    v-bind="settings"
  >
    <template v-slot:rightContentRender>
      <right-content
        :top-menu="settings.layout === 'topmenu'"
        :theme="settings.theme"
      />
    </template>

    <template v-slot:footerRender>
      <global-footer />
    </template>

    <router-view />
  </pro-layout>
</template>

**Comment by zyp1573** [comment]
> ![Snipaste_2020-06-09_09-58-19](https://user-images.githubusercontent.com/9797826/84097643-c730aa80-aa37-11ea-8609-a894d06b896c.png)
> 
> <pro-layout
> title =“ xxxxxx”
> ：menus =“ menus”
> ：collapsed =“ collapsed”
> ：mediaQuery =“ query”
> ：isMobile =“ isMobile”
> ：handleMediaQuery =“ handleMediaQuery”
> ：handleCollapse =“ handleCollapse”
> ：logo =“ logoRender “
> v-bind =” settings“
> 
> > 
> 
> ```
> <template v-slot:rightContentRender>
>   <right-content
>     :top-menu="settings.layout === 'topmenu'"
>     :theme="settings.theme"
>   />
> </template>
> 
> <template v-slot:footerRender>
>   <global-footer />
> </template>
> 
> <router-view />
> ```

如果不使用i18n这样写就可以了   :i18nRender="(t) => t"

**Comment by sendya** [comment]
i18nRender 呢

**Comment by sendya** [comment]
不会使用的情况下，推荐参考 examples 代码

**Comment by yxdy1990** [comment]
嗯，通过阅读源码及对比，确实是没有配置i18nRender的原因，我不准备做国际化，按照@zyp1573的提示，添加 :i18nRender="(t) => t"就好了。
非常感谢！

**Comment by sangokyoyou** [comment]
> :i18nRender="(t) => t"
我也遇到这个问题，源码里defaultI18nRender不起作用呀
