### ISSUE TITLE
vue 3 使用 异常

### ISSUE THREAD

**Issue by Arjen0925** [vueComponent/pro-layout#132]
vue3 中引用 会出现
![image](https://user-images.githubusercontent.com/13391605/124537482-8e3a5380-de4c-11eb-92a6-82f90aae61ba.png)

**Comment by sendya** [comment]
安装 less

**Comment by sendya** [comment]
不要随意调整 alias

**Comment by Arjen0925** [comment]
less 有安装 还是报错

**Comment by xwnwho** [comment]
less版本问题，https://github.com/vueComponent/pro-layout/issues/121
