### ISSUE TITLE
footerRender 判断问题

### ISSUE THREAD

**Issue by kwdiwt** [vueComponent/pro-layout#133]
```
<template v-slot:footerRender>
   <global-footer />
</template>
```
注释掉这个后，审查元素依然有    不应该渲染出来的
```
<footer class="ant-layout-footer"></footer>
```
BasicLayout.tsx 里面这行{footerRender && footerRender(props)} 被转为js后
footerRender !== false && h(Layout.Footer, [isFun(footerRender) && footerRender(h) || footerRender]) || null
footerRender没有是undefined 第一条件成立了 
不确定是不是ts问题 没怎么用过ts

**Comment by sendya** [comment]
footerRender 不传递时，渲染默认 footer 。不存在说不应该渲染

**Comment by kwdiwt** [comment]
> footerRender 不传递时，渲染默认 footer 。不存在说不应该渲染

没用到的东西 要渲染干嘛？ 这边还需要用样式隐藏掉

**Comment by sendya** [comment]
> 没用到的东西 要渲染干嘛？ 这边还需要用样式隐藏掉

关闭是这样的行为才对

```vue
<pro-layout :footerRender="false"> ... </pro-layout>
```
