### ISSUE TITLE
警告: 找不到’./locale‘

### ISSUE THREAD

**Issue by xwnwho** [vueComponent/pro-layout#134]
Module not found: Error: Can't resolve './locale' in '@ant-design-vue\pro-layout\dist'
不影响使用

**Comment by xwnwho** [comment]
版本：3.1.0-alpha.1

**Comment by sendya** [comment]
怎么用的？ 提供复现

**Comment by xwnwho** [comment]
这个告警浏览器不会出来，我在codesandbox，没有看到浏览器有报错，本地也是。本地启动服务的时候，cmd会提示，应该是加载moment,locale语言的告警，Module not found: Error: Can't resolve './locale' in 'D:\projects\practice\test\node_modules\@ant-design-vue\pro-layout\dist'

**Comment by xwnwho** [comment]
我测试的地址: https://codesandbox.io/s/headless-smoke-ql593?file=/src/main.js

**Comment by sendya** [comment]
![image](https://user-images.githubusercontent.com/5404542/125278656-93fcd100-e345-11eb-8c77-334e4a904a29.png)

pro-layout 应该没引入 moment 你在确认下？

**Comment by xwnwho** [comment]
![image](https://user-images.githubusercontent.com/80031313/125376819-61db8580-e3be-11eb-916a-8efdff50d2d3.png)
这是我本地引用的文件

**Comment by sendya** [comment]
无法复现警告内容， 建议提供在线可运行复现

**Comment by xwnwho** [comment]
![image](https://user-images.githubusercontent.com/80031313/125402321-da563c80-e3e6-11eb-883a-78b3bfded182.png)
这是我通过rollup-plugin-visualizer插件生成分析图，moment是被build进去了的

**Comment by sendya** [comment]
try 3.1.0-alpha.2

**Comment by xwnwho** [comment]
好了
