### ISSUE TITLE
升级到最新版本ProLayout 自定义  breadcrumbRender 不能使用

### ISSUE THREAD

**Issue by airshiplay** [vueComponent/pro-layout#135]
``
<ProLayout>
<template #breadcrumbRender="{route,routes,paths}">
        <span v-if="routes.indexOf(route) === routes.length-1">  {{ i18nRender(route.breadcrumbName) }}</span>
        <RouterLink v-else :to="{ path: route.path }">
          {{ i18nRender(route.breadcrumbName) }}
        </RouterLink>
</template>
 </ProLayout>
``

BasicLayout.vue?25d6:53 Uncaught (in promise) TypeError: Cannot read property 'route' of undefined
    at eval (BasicLayout.vue?25d6:53)
    at Proxy.renderFnWithContext (runtime-core.esm-bundler.js?5c40:1124)
    at Ne (pro-layout.es.js?bf9a:1)
    at setup (pro-layout.es.js?bf9a:9)

**Comment by sendya** [comment]
老版本可以吗？

**Comment by sendya** [comment]
try 3.1.0-alpha.2

**Comment by airshiplay** [comment]
> 老版本可以吗？


之前的旧版本 3.0.0-beta.6 可以使用

> try 3.1.0-alpha.2

现在更新到 3.1.0-alpha.3 也不行


代码详见   [gitee](https://gitee.com/airlenet/ant-design-vue-pro)  

master分支为3.0.0-beta.6 可以正常显示    

feature-version 分支为 3.1.0-alpha.3 不能显示。http://localhost:8080/dashboard/workplace  没有显示breadcrumb

**Comment by airshiplay** [comment]
更新到最新  3.1.0-alpha.4  又不能使用了

**Comment by sendya** [comment]
升级到最新

**Comment by datoulei** [comment]
3.1.0版本不能使用

**Comment by ychost** [comment]
同，又不能用了,3.1.0

**Comment by sendya** [comment]
@datoulei @ychost  提供复现，不要在老 issue 试图跟”贴“
