### ISSUE TITLE
3.1.0.alpha TSX不支持

### ISSUE THREAD

**Issue by lihxhit** [vueComponent/pro-layout#136]
3.1.0 alpha 版本开始TSX跑不了，类型有问题

且不支持主题定制

**Comment by sendya** [comment]
一直没提供主题定制

**Comment by sendya** [comment]
只有 light dark 主题

**Comment by lihxhit** [comment]
我是说less配置modifyVars的primary-color不生效

**Comment by lihxhit** [comment]
关键是tsx问题，我现在把版本锁死在3.0.0-beta.12了

**Comment by xwnwho** [comment]
> 我是说less配置modifyVars的primary-color不生效

那是less-loader版本的问题,我记得6以上的配置便不同了

**Comment by xwnwho** [comment]
> 关键是tsx问题，我现在把版本锁死在3.0.0-beta.12了

如果是ProLayout的问题，建议使用import { ProLayout } from '@ant-design-vue/pro-layout',能解决

**Comment by lihxhit** [comment]
import { ProLayout } from '@ant-design-vue/pro-layout. 确实解决了tsx的类型问题

但是主题定制确实不生效了，因为你们现在的使用方式只能是全局导入css，而不是自动导入less。。。

**Comment by xwnwho** [comment]
> import { ProLayout } from '@ant-design-vue/pro-layout. 确实解决了tsx的类型问题
> 
> 但是主题定制确实不生效了，因为你们现在的使用方式只能是全局导入css，而不是自动导入less。。。

import '@ant-design-vue/pro-layout/dist/style.css' 放在main.js的最前面，可以用，我是这样使用的

**Comment by lihxhit** [comment]
> > import { ProLayout } from '@ant-design-vue/pro-layout. 确实解决了tsx的类型问题
> > 但是主题定制确实不生效了，因为你们现在的使用方式只能是全局导入css，而不是自动导入less。。。
> 
> import '@ant-design-vue/pro-layout/dist/style.css' 放在main.js的最前面，可以用，我是这样使用的

直接导入css是不支持antdv的主题定制的~要用less才可以~

**Comment by xwnwho** [comment]
> > > import { ProLayout } from '@ant-design-vue/pro-layout. 确实解决了tsx的类型问题
> 
> > > 但是主题定制确实不生效了，因为你们现在的使用方式只能是全局导入css，而不是自动导入less。。。
> 
> > 
> 
> > import '@ant-design-vue/pro-layout/dist/style.css' 放在main.js的最前面，可以用，我是这样使用的
> 
> 
> 
> 直接导入css是不支持antdv的主题定制的~要用less才可以~

那就不清楚了，我这样改了基础配色，有效果

**Comment by lihxhit** [comment]
所有老板会改吗？单纯把package.json的exports删了也行啊

**Comment by lihxhit** [comment]
> 一直没提供主题定制

意思就是不支持less导入了

**Comment by sendya** [comment]
@ant-design-vue/pro-layout@3.1.0-alpha.4

引入 `dist/styles.less` 试试

**Comment by lihxhit** [comment]
> @ant-design-vue/pro-layout@3.1.0-alpha.4
> 
> 引入 `dist/styles.less` 试试

引入less样式有问题，css没问题但是不支持自定义主题
还有自定义面包屑也不显示
