### ISSUE TITLE
rightContentRender 插槽中使用子组件，v-model:collapsed="collapsed" 第二次无效

### ISSUE THREAD

**Issue by jekip** [vueComponent/pro-layout#137]
pro-layout 默认传入子组件是 false，在子组件中出触发 $emit('update:collapsed', !collapsed)"，第一次生效，再次切换则无效了，当把这个组件移到pro-layout同级，多次切换菜单都正常收起展开

**Comment by sendya** [comment]
你能确定 collapsed 变量是动态的吗

**Comment by jekip** [comment]
是动态的，把rightContentRender 插槽中子组件，移到和pro-layout同级，切换就正常生效

**Comment by sendya** [comment]
贴代码

**Comment by sendya** [comment]
太久没有反馈，默认为已解决，如果尚未解决，请发新 issue
