### ISSUE TITLE
怎么自定义menu的icon

### ISSUE THREAD

**Issue by linwuhu** [vueComponent/pro-layout#145]
menu的icon需要用到iconfont

**Comment by gaopeak** [comment]
看组件文档

**Comment by gaopeak** [comment]
看menu 组件文档

**Comment by jianshen-weo** [comment]
3.1.0-beta.2版本中，menuItemRender插槽自定义渲染无效，我看下载的源码例子里面也是没有效果的
`<template #menuItemRender="{ item, icon }">
      <a-menu-item
        :key="item.path"
        :disabled="item.meta?.disabled"
        :danger="item.meta?.danger"
        :icon="icon"
      >
        <router-link :to="{ path: item.path }">
          <div class="a-menu-item-title">
            <a-badge count="5" dot>
              {{ item.meta.title }}
            </a-badge>
          </div>
        </router-link>
      </a-menu-item>
    </template>`

**Comment by sendya** [comment]
updated : https://github.com/vueComponent/pro-layout/releases/tag/3.1.0-beta.6
