### ISSUE TITLE
菜单栏如何增加数字提示

### ISSUE THREAD

**Issue by xp31** [vueComponent/pro-layout#147]
能不能在菜单上增加一个红色的数字提示功能，或者如何实现

**Comment by sendya** [comment]
试试 props menuContentRender

**Comment by xp31** [comment]
> 试试 props menuContentRender

vue pro的框架，没有menuContentRender这个

**Comment by sendya** [comment]
这是 next 版本才提供的功能

下次提问，请说明环境，免得互相浪费时间

**Comment by xp31** [comment]
那能否在master版本也增加呢？

**Comment by sendya** [comment]
vue2 版本已经稳定使用很久了，不在做功能新增，重心主要在开发 vue3 版本，你可以实现好提个 PR 过来

**Comment by xp31** [comment]
谢谢老板
