### ISSUE TITLE
menuItemRender插槽自定义渲染无效

### ISSUE THREAD

**Issue by jianshen-weo** [vueComponent/pro-layout#151]
3.1.0-beta.2版本中，menuItemRender插槽自定义渲染无效，我看下载的源码例子里面也是没有效果的
<template #menuItemRender="{ item, icon }"> <a-menu-item :key="item.path" :disabled="item.meta?.disabled" :danger="item.meta?.danger" :icon="icon" > <router-link :to="{ path: item.path }"> <div class="a-menu-item-title"> <a-badge count="5" dot> {{ item.meta.title }} </a-badge> </div> </router-link> </a-menu-item> </template>

**Comment by gaopeak** [comment]
你都说了3.1.0-beta.2 ，等正式版，

**Comment by sendya** [comment]
@gaopeak  请问你是？

**Comment by gaopeak** [comment]
> @gaopeak 请问你是？
不是我问的，我是回答楼上，我没问题，

**Comment by gaopeak** [comment]
> @gaopeak 请问你是？

我回答楼上的

**Comment by sendya** [comment]
@jianshen-weo 先退回 beta.1，beta.2 做了 props 检查，menu 的自定义 render 默认是 false 所以 slot 被忽略了

**Comment by jianshen-weo** [comment]
> @jianshen-weo 先退回 beta.1，beta.2 做了 props 检查，menu 的自定义 render 默认是 false 所以 slot 被忽略了

**Comment by jianshen-weo** [comment]
我现在用vite创建了个项目，引用了beta.1，ant-design-vue引用的2.2.2版本，程序正常编译，但是浏览器一访问，页面空白，控制台报错如下：
`Uncaught (in promise) TypeError: Cannot read property 'prefixCls' of undefined
    at setup47 (MenuItem.js:46)
    at callWithErrorHandling (runtime-core.esm-bundler.js:6990)
    at setupStatefulComponent (runtime-core.esm-bundler.js:6606)
    at setupComponent (runtime-core.esm-bundler.js:6562)
    at mountComponent (runtime-core.esm-bundler.js:4421)
    at processComponent (runtime-core.esm-bundler.js:4396)
    at patch (runtime-core.esm-bundler.js:3991)
    at mountChildren (runtime-core.esm-bundler.js:4187)
    at processFragment (runtime-core.esm-bundler.js:4355)
    at patch (runtime-core.esm-bundler.js:3984)`
main.ts引用如下：
`import "ant-design-vue/es/style";
import { ConfigProvider, Button } from 'ant-design-vue';

import { createApp } from "vue";
import router from '@/router';
import icons from '@/icons';
import App from "@/App.vue";
// import Antd from "@/plugin/ant.js"; // 引入ant.js
import '@ant-design-vue/pro-layout/dist/style.less'; // pro-layout css or style.less
import ProLayout, { PageContainer } from '@ant-design-vue/pro-layout';

const app = createApp(App);
app.use(router);
app.use(icons);
// app.use(Antd);
app.use(ConfigProvider);
app.use(Button);
app.use(ProLayout);
app.use(PageContainer);
app.mount("#app");`
我看了下examples，是可以正常打开的，奇怪了>-<!

**Comment by sendya** [comment]
ant-design-vue 升级到最新，vue用 3.2.x

**Comment by sendya** [comment]
再不会就参考  
https://github.com/sendya/preview-pro

**Comment by jianshen-weo** [comment]
> 再不会就参考
> https://github.com/sendya/preview-pro

好的，感谢！！！

**Comment by sendya** [comment]
3.1.0-beta.3
