### ISSUE TITLE
less布局

### ISSUE THREAD

**Issue by siluozhang516** [vueComponent/pro-layout#153]
引入less后，layout设置为top，子级菜单不显示 import '@ant-design-vue/pro-layout/dist/style.less'

**Comment by sendya** [comment]
版本

**Comment by siluozhang516** [comment]
@sendya  less @2.7.3 ， ant-design-vue@2.2.3

**Comment by sendya** [comment]
pro-layout 版本呢？less太低了，升4。

还有，以后这种问题建议提供复现仓库

**Comment by sendya** [comment]
建议参考这个作为项目模板

https://github.com/sendya/preview-pro
