### ISSUE TITLE
如何隐藏第一级路由不渲染到菜单，设置了hideInMenu没效果？

### ISSUE THREAD

**Issue by doitcore** [vueComponent/pro-layout#158]
如何隐藏第一级路由不渲染到菜单，设置了hideInMenu没效果？比如登录页和404页

**Comment by sendya** [comment]
menuData 是由你自己绑定到 pro-layout 的，你可以过滤掉不要的数据之后再绑定

**Comment by doitcore** [comment]
已通过过滤数据解决，找到方法了，可以用内置函数：clearMenuItem
