### ISSUE TITLE
顶部悬浮时 page-container 高度超出屏很多时，滚动条最后页面展示不完整

### ISSUE THREAD

**Issue by Sgenmi** [vueComponent/pro-layout#159]
version:v3.1.0
bug：   
  注： fixedHeader : true,
   
![image](https://user-images.githubusercontent.com/3337501/137084839-40b64085-498e-4bd5-ad9b-c91d593499d3.png)

**Comment by sendya** [comment]
无法复现，请提供复现

**Comment by Sgenmi** [comment]
```html
<page-container title="Page 1" sub-title="is a sub-title.">
    <template #content>
      <div>
        container.content
        <h1>{{ text }}</h1>
      </div>
      <span>page-content</span>
      <div v-for=" t in 50">page-content</div>
      <a-button @click="handleClick">Button</a-button>
    </template>
  </page-container>
```

我是不是用错了，是不是不要用 content 直接放在template 外面

**Comment by sendya** [comment]
content slot 是 page-header 的 content 不是默认内容

**Comment by sendya** [comment]
可以看一下 examples

https://github.com/vueComponent/pro-layout/blob/next/examples/views/page1.vue#L1-L12

**Comment by Sgenmi** [comment]
> content slot 是 page-header 的 content 不是默认内容

好的。3Q。已解决
