### ISSUE TITLE
navTheme 参数配置为dark不生效

### ISSUE THREAD

**Issue by jekip** [vueComponent/pro-layout#163]
![image](https://user-images.githubusercontent.com/19426584/138312520-89ff5747-2146-4124-a390-b2bf3dd854e5.png)
会出现2个header，我发现 header设置dark样式是生效了，但是被他内部的，ant-pro-global-header 盒子白色背景给覆盖了（不一定准确）

**Comment by sendya** [comment]
不知道你在表达什么，建议提供复现，或者参考 examples 代码


side dark
![image](https://user-images.githubusercontent.com/5404542/138381352-22114f4b-45b7-45fd-b107-e7d460d154ac.png)

top dark|light
![image](https://user-images.githubusercontent.com/5404542/138381437-3947d1af-7bcc-4052-8f26-eb9250da5a34.png)

mix dark
![image](https://user-images.githubusercontent.com/5404542/138381525-72f695ad-5cab-4d5e-9a73-7c8fcdaaf30b.png)

**Comment by jekip** [comment]
可能是我搞错了，`layout`  为 ` side` 的时候，设置 ` navTheme`  为  `dark`，不生效，设计就是如此吧？

**Comment by sendya** [comment]
你看一下 examples，怎么会不生效呢？  navTheme 是导航主题，你是不是搞错了？ 怎么会跟 header 有关系，只有菜单是 top 的时候，才是 navTheme 才会控制到 header

**Comment by jekip** [comment]
抱歉，是理解错了，菜单模式 `side` 和 `mix` ，如何实现，也能控制，header 主题色，能否在提供一个配置，`headerTheme` ?

**Comment by sendya** [comment]
你试一下 ？

**Comment by jekip** [comment]
并非`bug`，设计如此
