### ISSUE TITLE
请问菜单，能否支持一下外部链接配置？

### ISSUE THREAD

**Issue by jekip** [vueComponent/pro-layout#164]
比如：`menuData` 里面支持 `render` ，或者借助 `RouteRecordRaw` 中 `meta` 来实现这个功能？

**Comment by sendya** [comment]
meta 里配置 `target: true` 并且 path 是 完整的 http[s] 链接即可成为 router 外链，另外  就算不支持，layout 提供了 MenuItemRender, MenuSubItemRender 可以自由控制渲染，为什么要在 menuData 里支持 render ？

**Comment by sendya** [comment]
你可以参考一下这个代码段

https://github.com/vueComponent/pro-layout/blob/next/examples/layouts/CustomLayout.vue#L38-L53

外联底层实现
https://github.com/vueComponent/pro-layout/blob/next/src/SiderMenu/BaseMenu.tsx#L216-L220

**Comment by jekip** [comment]
谢谢，我自行处理了一下 `menuData` 中 `path`  基于底层实现了
