### ISSUE TITLE
[Feature] WaterMark 采用 ES6 解构了 props 导致 props失去响应式

### ISSUE THREAD

**Issue by kkaaddff** [vueComponent/pro-layout#173]
### 🥰 需求描述 

在很多情况下水印的字段来自异步请求
水印也会有更改的需求
通过改变 props 响应式的更改水印是符合预期的

### 🧐 解决方案 Solution

采用`toRefs` 解构值
[vue3 setup props](https://v3.cn.vuejs.org/guide/composition-api-setup.html#props)

**Comment by kkaaddff** [comment]
我先提个PR吧？ @sendya

**Comment by sendya** [comment]
👍 这个组件以前是写的函数式组件， 函数式组件本身不带状态，可以直接解构使用。
后来换成了 `defineComponent` 忘了处理 props

**Comment by kkaaddff** [comment]
> 👍 这个组件以前是写的函数式组件， 函数式组件本身不带状态，可以直接解构使用。 后来换成了 `defineComponent` 忘了处理 props

关于水印的小feature：
       后期考不考虑在水印上添加事件绑定。防止用户篡改

**Comment by sendya** [comment]
防君子 防不住小人，没有太大的必要，如果有这种需求的，独立写一个可能会更好定制
