### ISSUE TITLE
[Question] Help

### ISSUE THREAD

**Issue by LnksW** [vueComponent/pro-layout#174]
### 🧐 问题描述 Problem Description

左侧菜单的icon是否支持随菜单颜色变化而变化
使用的版本3.1
另一疑问是是否还有办法像2版本那样更改主题色
### 🚑 其他信息 Other information

![image](https://user-images.githubusercontent.com/42366809/142344388-e922c179-7e3f-4478-98f1-7c38d86fcc4e.png)

**Comment by sendya** [comment]
![image](https://user-images.githubusercontent.com/5404542/142345695-4c7cdbdf-240c-4522-b8e7-20b5a17e08ce.png)

**Comment by LnksW** [comment]
@sendya  请问使用关键在哪，我未能发现

**Comment by sendya** [comment]
你没能提供更多信息，我也未能发现你的问题

**Comment by LnksW** [comment]
已解决
