### ISSUE TITLE
设置breakpoint时，控制台有Vue warn，请问该如何设置breakpoint？

### ISSUE THREAD

**Issue by ly-sniper** [vueComponent/pro-layout#177]
### 🧐 问题描述 
**Dev**模式下，设置breakpoint，`<pro-layout breakpoint="lg">`
控制台出现警告：
[Vue warn]: Invalid prop: type check failed for prop "breakpoint". Expected Object | Boolean, got String with value "lg".

### 🚑 其他信息 
pro-layout版本：3.1.6
BasicLayout.d.ts中，breakpoint: false | "xs" | "sm" | "md" | "lg" | "xl" | "xxl" | undefined;

**Comment by sendya** [comment]
目前 breakpoint 没有实际控制，请问你是需要做什么需求吗？

**Comment by ly-sniper** [comment]
@sendya 感谢回复。
我是为了实现根据页面宽度来是实现左侧菜单的响应性布局（即左侧菜单根据**页面宽度**进行**收缩**，**隐藏**等效果）
我发下把**breakpoint**设置为**lg**可以得到我想要的效果，但是不明白为什么要把breakpoint定义为`Object | Boolean`

**Comment by sendya** [comment]
我在本地做了测试，发现实际上现在并没有把 sider 的 `breakpoint` 响应事件接收起来， 因为目前的设计上，collapsed 变成了 v-model 受控，全权交出给用户控制了，我在后续更新中在看下怎么实现这个 prop 把，目前不建议使用

**Comment by ly-sniper** [comment]
@sendya ，
npm安装`ant-design-vue\pro-layout@3.1.6`，pro-layout.es.js中
```
breakpoint: {
    type: [Object, Boolean],
    default: () => false
  }
```
但是手动build`Next`分支，pro-layout.es.js中
```
breakpoint: {
    type: [Object, String, Boolean],
    default: () => false
  }
```
npm包中breakpoint的type少了 `String`，请问是什么原因呢
