### ISSUE TITLE
[Feature] ant-design-vue 兼容使用 v3 版本

### ISSUE THREAD

**Issue by candy-Tong** [vueComponent/pro-layout#179]
### 🥰 需求描述 Description of Requirement

目前package.json，依赖的仍是 v2 版本的ant-design-vue，如果外部使用的是 v3 的ant-design-vue，则会有两个不同的版本
https://github.com/vueComponent/pro-layout/blob/next/package.json#L40

**Comment by sendya** [comment]
roadmap  建议看完

https://github.com/vueComponent/pro-layout/discussions/172
