### ISSUE TITLE
examples的依赖报错

### ISSUE THREAD

**Issue by yoder** [vueComponent/pro-layout#18]
These dependencies were not found:

* @ant-design/icons/lib/outline/AlignLeftOutline in ./src/core/antd/icons.js
* @ant-design/icons/lib/outline/ArrowLeftOutline in ./src/core/antd/icons.js
* @ant-design/icons/lib/outline/ArrowRightOutline in ./src/core/antd/icons.js
* @ant-design/icons/lib/outline/CheckOutline in ./src/core/antd/icons.js
* @ant-design/icons/lib/outline/CloseOutline in ./src/core/antd/icons.js
* @ant-design/icons/lib/outline/CopyrightOutline in ./src/core/antd/icons.js
* @ant-design/icons/lib/outline/DashboardOutline in ./src/core/antd/icons.js
* @ant-design/icons/lib/outline/DownOutline in ./src/core/antd/icons.js
* @ant-design/icons/lib/outline/EllipsisOutline in ./src/core/antd/icons.js
* @ant-design/icons/lib/outline/GithubOutline in ./src/core/antd/icons.js
* @ant-design/icons/lib/outline/GlobalOutline in ./src/core/antd/icons.js
* @ant-design/icons/lib/outline/LeftOutline in ./src/core/antd/icons.js
* @ant-design/icons/lib/outline/LoadingOutline in ./src/core/antd/icons.js
* @ant-design/icons/lib/outline/LogoutOutline in ./src/core/antd/icons.js
* @ant-design/icons/lib/outline/MenuFoldOutline in ./src/core/antd/icons.js
* @ant-design/icons/lib/outline/MenuUnfoldOutline in ./src/core/antd/icons.js
* @ant-design/icons/lib/outline/NotificationOutline in ./src/core/antd/icons.js
* @ant-design/icons/lib/outline/QuestionCircleOutline in ./src/core/antd/icons.js
* @ant-design/icons/lib/outline/ReloadOutline in ./src/core/antd/icons.js
* @ant-design/icons/lib/outline/RightOutline in ./src/core/antd/icons.js
* @ant-design/icons/lib/outline/SettingOutline in ./src/core/antd/icons.js
* @ant-design/icons/lib/outline/SmileOutline in ./src/core/antd/icons.js
* @ant-design/icons/lib/outline/UserOutline in ./src/core/antd/icons.js
* @ant-design/icons/lib/outline/VideoCameraOutline in ./src/core/antd/icons.js

**Comment by sendya** [comment]
引入 @ant-design/icons v2 版本的依赖
