### ISSUE TITLE
动态路由情况下如何自定义更改菜单icon

### ISSUE THREAD

**Issue by chf-gh** [vueComponent/pro-layout#181]
后台配置的动态路由，只能选择antd的icon图标，现在想更换为iconfont的图标如何更改？
![image](https://user-images.githubusercontent.com/20312535/145673047-ce409b14-8226-4c25-945a-fdf8e6fb9d8c.png)
网上说的试了一堆都没用。静态路由情况下在前端文件配置图标可以生效，但是后台的动态路由不行。怎么办？

**Comment by sendya** [comment]
导入的 svg 做成一个 kv map 供后端提供 key 来控制 icon。目前不支持其他方案。如有需要可以 PR
