### ISSUE TITLE
发现路由菜单第一层展开的时候同级可以自动关闭 当第二层展开的时候 同级的第二层就没法自动关闭了  不统一 都是children嵌套

### ISSUE THREAD

**Issue by yehoan** [vueComponent/pro-layout#184]
![image](https://user-images.githubusercontent.com/22631753/146627997-8cd6ecad-454c-45f1-b69d-d213f25607f8.png)
当绿色箭头的展开的时候同级会自动关闭  当红色箭头的展开的时候同级的展开的时候不会自动关闭  都是用children嵌套的   想知道为什么会这样 怎么才能保持统一 都是和第一级一样

**Comment by yehoan** [comment]
"@ant-design-vue/pro-layout": "^1.0.1",

**Comment by sendya** [comment]
提供复现仓库
