### ISSUE TITLE
[BUG] Report bug pro-layout v-model:isMobile 切换设备为手机时，isMobile值没有变化

### ISSUE THREAD

**Issue by niesai** [vueComponent/pro-layout#188]
pro-layout v-model:isMobile 没有监听到变化
`<pro-layout
        :layout="layoutMode"
        :theme="navTheme"
        :navTheme="navTheme"
        :headerTheme="navTheme"
        :menuData="menuData"
        :splitMenus="true"
        :fixedHeader="fixedHeader"
        :fixSiderbar="fixedSidebar"
        v-model:isMobile="isMobile"
        v-model:collapsed="collapsed"
        v-model:openKeys="openKeys"
        v-model:selectedKeys="selectedKeys"
    >
        <template v-slot:menuHeaderRender>
            <div class="logo">
                <img src="../assets/logo.png" alt="" />
                <h1>{{ title }}</h1>
            </div> 
        </template>
        <template v-slot:rightContentRender>
            <right-content
                :top-menu="layoutMode === 'top'"
                :is-mobile="isMobile"
                :theme="navTheme"
            />
        </template>
        <div class="bread">
            <a-breadcrumb :routes="routes">
                <template v-slot:itemRender="{ route }">
                    <span>
                        {{ route.breadcrumbName }}
                    </span>
                </template>
            </a-breadcrumb>
        </div>
        <setting-drawer v-if="isDev"></setting-drawer>
        <router-view />
    </pro-layout>`

**Comment by sendya** [comment]
pro-layout 没提供 v-model，请参考文档使用

**Comment by niesai** [comment]
那有没有其他办法判断isMobile是否变化

**Comment by sendya** [comment]
目前没有。 使用场景是什么？

isMobile 现在是内置的熟悉。ProLayout 会在根节点上增加 media-query 提供 class 的 screen-xl, screen-sm 等类名
做样式变化可以直接根据类名处理对应的样式
