### ISSUE TITLE
collapsed 状态下面路由不能正常跳转

### ISSUE THREAD

**Issue by ychost** [vueComponent/pro-layout#199]
版本：  
```jsnon
"@ant-design-vue/pro-layout": "^3.1.12",
"@ant-design/icons-vue": "^6.0.1",
"ant-design-vue": "^2.2.8",
```
将下面的样式注释掉，可恢复跳转
![image](https://user-images.githubusercontent.com/16224686/153854657-a449edfc-2797-410b-adca-acc7d42ef950.png)

**Comment by sendya** [comment]
确实点了无法切换，但应该是跟渲染 router-link 相关

**Comment by sendya** [comment]
升级到 3.1.13 或升级 ant-design-vue@3.1 + pro-layout@3.2 应该能解决
