### ISSUE TITLE
[BUG] menuItemRender 不能正常使用

### ISSUE THREAD

**Issue by ymy0622** [vueComponent/pro-layout#200]
### 🐛 Bug 描述 Bug description

vuecli+pnpm创建的vue3项目（vuecli+yarn的项目经测试，正常）

使用menuItemRender时会报错，layout为仓库中examples的CustomLayout：
1. [Vue warn]: injection "Symbol(menuContextKey)" not found. 
2. TypeError: Cannot read properties of undefined (reading 'prefixCls')

### 🚑 其他信息 Other information

"@ant-design-vue/pro-layout": "^3.1.13",
"ant-design-vue": "^3.0.0-beta.13",

- 报错截图：

![image](https://user-images.githubusercontent.com/54923146/157216073-35ecb2d2-d8c9-4a0a-bd92-16bd1f8afdee.png)
![image](https://user-images.githubusercontent.com/54923146/157216136-456ac6d6-cbe2-4208-8a7c-22a78aa554f2.png)

**Comment by ymy0622** [comment]
复现仓库：https://github.com/TomatoYakult/pro-layout-issues

**Comment by sendya** [comment]
"ant-design-vue" 用 2x 谢谢。暂不支持 3x
