### ISSUE TITLE
pro-layout使用menuRender只是渲染菜单样式吗

### ISSUE THREAD

**Issue by simpletonOflove** [vueComponent/pro-layout#202]
### 🧐 问题描述 Problem Description

pro-layout使用menuRender使用自定义菜单组件，但写的select方法置空selectedKeys不生效
### 🚑 其他信息 Other information

![1647245400(1)](https://user-images.githubusercontent.com/87957659/158130833-da4d5304-c60f-4c73-ae68-70ec966f4c51.png)
![1647245443(1)](https://user-images.githubusercontent.com/87957659/158131105-cc9758f0-e033-4563-aad2-ad8e316b81ee.png)

**Comment by sendya** [comment]
使用该 slot 需要自行管理 slot 中组件的状态，比如下面这些属性：
可以直接参考源码中的 SiderMenu 渲染 BaseMenu 是如何做的

```
          collapsed={collapsed}
          openKeys={openKeys}
          selectedKeys={selectedKeys}
          openOnceKey={openOnceKey}
          onOpenChange={openChange}
          onSelect={select}
```
