### ISSUE TITLE
[Question] 类如pro-table、pro-form...有roadmap吗？

### ISSUE THREAD

**Issue by buqiyuan** [vueComponent/pro-layout#204]
hello！感谢你的付出！table和form在后台管理系统中是相对核心的部分，希望pro-table、pro-form这两个重装组件能早日提上日程，有需要的话，我也可以参与你们的共建中去。

**Comment by sendya** [comment]
欢迎 PR

**Comment by buqiyuan** [comment]
👌 有空提一个

**Comment by InfernalAzazel** [comment]
@sendya  I'm looking forward to the same from login template as the react version. It's too convenient
