### ISSUE TITLE
[BUG] pro-layout 头部在fixedHeader: true布局无法自适应

### ISSUE THREAD

**Issue by InfernalAzazel** [vueComponent/pro-layout#206]
### 🐛 Bug 描述 Bug description
 const state = reactive({
      menuData,
      splitMenus: true,
      // title: 'ProLayout',
      // logo: 'https://alicdn.antdv.com/v2/assets/logo.1ef800a8.svg',
      navTheme: 'light',
      layout: 'side',
      fixSiderbar: true,
      fixedHeader: true,  //固定后布局无法自适应
    });
效果 请运行 [pro-components](https://github.com/vueComponent/pro-components) 例子代码

### 🏞 期望结果 Desired result
我期望是 左侧栏在收缩时头部栏下面那个栏 能满屏

### 🚑 其他信息 Other information
![image](https://user-images.githubusercontent.com/40333954/159533895-dffa2583-18c7-4cb8-a967-d2e66b386160.png)

**Comment by InfernalAzazel** [comment]
补充一点  fixSiderbar: true, fixedHeader: true, 希望作者添加说明文档，看了很多次文档想固定左侧栏，下载github代码才发现运行后找为什么作者的可以固定我的确不能。

**Comment by sendya** [comment]
反馈问题请表明版本，你描述的内容在最新版本中无法复现。是否能提供一个复现仓库之类的？

**Comment by sendya** [comment]
![image](https://user-images.githubusercontent.com/5404542/159628782-b45a27c3-7795-4cf4-bb05-f638bce77400.png)

**Comment by InfernalAzazel** [comment]
是 3.x 版本, 请你往下滚动，然后收缩。

**Comment by sendya** [comment]
update 3.2.0-rc.1
