### ISSUE TITLE
[Question] 请问如何变更菜单宽度

### ISSUE THREAD

**Issue by kdays** [vueComponent/pro-layout#207]
### 🧐 问题描述 Problem Description
在ant design vue里 修改菜单宽度我看是直接修改了menu组件里的width
请问一下 在ProLayout@next中 如何传入menu的style呢

非常感谢

**Comment by sendya** [comment]
应该是 siderWidth ，你可以看一下 props

**Comment by kdays** [comment]
非常感谢，确实是siderWidth，解决了
