### ISSUE TITLE
[Question] 更新目前版本后，左侧菜单无法支持一直只有一个打开

### ISSUE THREAD

**Issue by apgk** [vueComponent/pro-layout#209]
### 🧐 问题描述 Problem Description
左侧菜单 无法保留只有一个打开问题

1.官方演示是支持变更菜单，旧的就会收缩，打开点击项，
2.但目前库中代码下载后运行，点击过的菜单都会打开不会折叠

**Comment by sendya** [comment]
现在 openKeys 已经交给用户管理，自行控制 openKeys 的数据就可以控制菜单的折叠/展开。

**Comment by apgk** [comment]
> 现在 openKeys 已经交给用户管理，自行控制 openKeys 的数据就可以控制菜单的折叠/展开。

怎么操作，有教程吗,antd vue pro 版本的

**Comment by sendya** [comment]
你说的 “目前版本” 是哪个版本？ 能否提供完整的环境信息以便判断问题

**Comment by apgk** [comment]
> 你说的 “目前版本” 是哪个版本？ 能否提供完整的环境信息以便判断问题

 "dependencies": {
    "@ant-design-vue/pro-layout": "1.0.11",
    "@ant-design/icons": "^4.6.4",
    "@antv/data-set": "^0.10.2",
    "@antv/g2plot": "^2.3.23",
    "ant-design-vue": "^1.7.8",

**Comment by sendya** [comment]
只有在路由发生变化的时候，才会关闭 openKeys， 设计如此。

如果你实在需要打开一个就关闭一个菜单，可以自行控制 openKeys 属性，将该属性自主控制后，需要自行控制来自 pro-layout 的 菜单打开事件，并处理响应数据 同步更新到 openKeys 上，否则菜单将无法打开


如下： `handleOpenChange` 是一个 methods 里的函数，`openKeys` 是个数组，控制打开的菜单
```
<pro-layout
    :openChange="handleOpenChange"  
    :openKeys="openKeys"
/>
```

**Comment by my6521** [comment]
还是以前只打开一个的方式好
