### ISSUE TITLE
[Feature] New function

### ISSUE THREAD

**Issue by srrgithub** [vueComponent/pro-layout#210]
### 🥰 需求描述 Description of Requirement
文档好像都没啥内容。只能对着源码看。 展示效果也没有，挺不友好的，贴几张效果图片就可以拉。

**Comment by sendya** [comment]
应该是有的吧
https://github.com/vueComponent/pro-components/tree/next/packages/pro-layout

**Comment by sendya** [comment]
![image](https://user-images.githubusercontent.com/5404542/161374936-9d056e92-3fba-4f13-8f6d-1d19c4e5ace8.png)
