### ISSUE TITLE
[Feature] 1.x 版本上，可以做一个变更吗

### ISSUE THREAD

**Issue by tu6ge** [vueComponent/pro-layout#212]
### 🥰 需求描述 Description of Requirement
siderWidth 需要传 14rem，但是现在格式要求是数字

### 🧐 解决方案 Solution
改下 siderWidth prop 的格式要求为 any

### 🚑 其他信息 Other information
可以再发一个 1.x的小版本吗？我自己提pr

**Comment by sendya** [comment]
我不太清楚 siderWidth 直接传递给 Layout.Sider 组件是否会有异常，你可以先尝试一下~

**Comment by tu6ge** [comment]
能否提供一个 PR 指南，我可以通过这个指南方便的跑起来 fork 的代码，进而验证我所做的变更

**Comment by sendya** [comment]
升级到  [1.0.12](https://www.npmjs.com/package/@ant-design-vue/pro-layout/v/1.0.12) 即可
