### ISSUE TITLE
[Question] handleCollapse seems not working

### ISSUE THREAD

**Issue by zhangkx666** [vueComponent/pro-layout#213]
### 🧐 问题描述 Problem Description
[handleCollapse](https://github.com/vueComponent/pro-components/tree/next/packages/pro-layout#prolayout) seems not working.
Then I checked the source codes, but I can't find any codes for `handleCollapse`.
Is there any problem with my coding?

### 💻 示例代码 Sample code
```js
<template>
  <pro-layout
    ...
    :collapsed="state.collapsed"
    :handle-collapse="handleCollapsed"
  >
  ...
  </pro-layout>
</template>

<script>
import { reactive, ref } from 'vue'
export default {
  name: 'MainLayout',
  setup() {
    const state = reactive({
      collapsed: false,
      ...
    })
    const handleCollapsed = () => {
      state.collapsed = !state.collapsed
    }
    return { state, handleCollapsed }
  }
}
</script>
```

### 🚑 其他信息 Other information
Then I can only use the `collapsedButtonRender` slot to handle collapsed

```vue
<template #collapsedButtonRender>
  <div class="collapsedIcon" @click="handleCollapsed">
    <menu-fold-outlined v-if="!state.collapsed" />
    <menu-unfold-outlined v-else />
  </div>
</template>
```

**Comment by sendya** [comment]
文档没更新，直接按照 vue 风格监听即可 @collapse="boolean => void"

**Comment by zhangkx666** [comment]
> 文档没更新，直接按照 vue 风格监听即可 @collapse="boolean => void"

```
@collapse="handleCollapsed"
```
我改这样了，然而新的报错~
![image](https://user-images.githubusercontent.com/13268310/163812000-dea89827-4998-4b7d-928c-352781506ba6.png)

![image](https://user-images.githubusercontent.com/13268310/163811898-9058b373-4114-4858-9859-5df3474c5a16.png)

**Comment by sendya** [comment]
升到 3.2.1

ref https://github.com/vueComponent/pro-components/releases/tag/3.2.1
