### ISSUE TITLE
[BUG] layout: 'side' & fixSiderbar: false 时 siderbar 的z-index问题

### ISSUE THREAD

**Issue by zhangkx666** [vueComponent/pro-layout#214]
### 🐛 Bug 描述 Bug description
layout: 'side'
fixSiderbar: false
配置这两项时，siderbar看起来怪怪的，如图：

![image](https://user-images.githubusercontent.com/13268310/163700587-b7705bdc-0a80-4033-97b3-8aea64cd1c53.png)

### 🏞 期望结果 Desired result
![image](https://user-images.githubusercontent.com/13268310/163700597-a4d0edd5-a68d-41d6-9712-5cd4eba61293.png)

### 🚑 其他信息 Other information
加上z-index 的css后貌似正常了
```css
.ant-pro-sider {
  z-index: 20;
}
```

**Comment by sendya** [comment]
我观察 react antd procomponents 官方版本也是如此

![image](https://user-images.githubusercontent.com/5404542/163771632-8db9a58c-12cd-4a2e-ad82-af4c8362f597.png)

可以临时性的修正一下，但官方渠道没修正之前，本修正方案不会作为标准方案供后续兼容。（后续如果官方出了修正，会直接同步官方的修正 不兼容当前修正的实现方式）

如果急需，你可以直接通过样式添加，无需等待 pro 库发版。

**Comment by zhangkx666** [comment]
ok
