### ISSUE TITLE
[BUG] 在vue 3.2.33版本下报错

### ISSUE THREAD

**Issue by Kerbores** [vueComponent/pro-layout#215]
### 🐛 Bug 描述 Bug description
将vue升级至 3.2.33时打开页面报错,错误信息如下:

`
[Vue warn]: inject() can only be used inside setup() or functional components.
`
`
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'getPrefixCls')
`

### 🏞 期望结果 Desired result

控制台不报错,页面正常显示

### 🚑 其他信息 Other information
![控制台报错](https://user-images.githubusercontent.com/6072582/163740053-c72618ac-9de8-4531-824c-8ce7b7331e7e.png)

**Comment by sendya** [comment]
无法复现你的问题，建议你重新安装依赖

https://sendya.github.io/preview-pro/#/version

**Comment by xiaolu-coding** [comment]
同样的问题

**Comment by zhangkx666** [comment]
也遇到同样的问题，但是貌似把node_modules删掉后重新安装就消失了

**Comment by 7polo** [comment]
也是同样问题

**Comment by nxnminieye** [comment]
也是同样问题

**Comment by hayabusa2009** [comment]
> 无法复现你的问题，建议你重新安装依赖
> 
> https://sendya.github.io/preview-pro/#/version

重装3.2.1 3.2.2仍出现这个error

**Comment by zhangkx666** [comment]
@sendya  vue 3.2.34及后边的版本都又有这个问题了

**Comment by 94ashui** [comment]
"vue": "^3.2.37"
 "ant-design-vue": "^3.2.9"
 "@ant-design-vue/pro-layout": "^3.2.2"
同样有这个问题 @sendya

**Comment by 94ashui** [comment]
@zhangkx666 问题解决了么？

**Comment by Kchengz** [comment]
遇到同样的问题，以下两种引入方式出现问题
方式一：
`import Form from "ant-design-vue/lib/form"
import FormItem from "ant-design-vue/lib/form/FormItem"
`
方式二：
`const Form = () => import("ant-design-vue/lib/form")
const FormItem = () => import("ant-design-vue/lib/form/FormItem")`


最后换成下面的引入方式就可以了：
`import { Form, FormItem } from "ant-design-vue";`
