### ISSUE TITLE
和ant一起用会重复打包ant-desgn-vue/es

### ISSUE THREAD

**Issue by Effyt** [vueComponent/pro-layout#218]
### 🥰 需求描述 Description of Requirement
和ant一起用会重复打包ant-desgn-vue/es

### 🧐 解决方案 Solution
要咋样才能不重复打包呢

### 🚑 其他信息 Other information

<img width="634" alt="image" src="https://user-images.githubusercontent.com/28506339/164582905-50003362-98b3-4684-bbf4-04ae6129a3b9.png">

- [ ]

**Comment by sendya** [comment]
prolayout必须引入一些 antd 的依赖才可以有效运行否则需要用户手动引入使用到的依赖，目前 prolayout 即使没加载 antd 也能渲染整个基础 prolayout。属于处理方案的问题了

目前无法解决，除非不用 vite ，如果有解决方案，欢迎PR。
