### ISSUE TITLE
PageContainer fixedHeader 被ProLayout header 遮挡

### ISSUE THREAD

**Issue by yushushu122** [vueComponent/pro-layout#219]
### 🧐 问题描述 Problem Description

PageContainer fixedHeader 被ProLayout header 遮挡

### 💻 示例代码 Sample code

<img width="543" alt="image" src="https://user-images.githubusercontent.com/9691688/164710783-f35745e3-dda2-4b54-a9b1-423d5658fa3a.png">
### 🚑 其他信息 Other information

<img width="1466" alt="image" src="https://user-images.githubusercontent.com/9691688/164710674-3465b399-c68a-4f4c-bf28-195ff7c3595a.png">

**Comment by sendya** [comment]
fixed 3.2.2  ref https://github.com/vueComponent/pro-components/releases/tag/3.2.2
