### ISSUE TITLE
菜单显示[Question] Help

### ISSUE THREAD

**Issue by Sgenmi** [vueComponent/pro-layout#226]
### 🧐 问题描述 Problem Description
![image](https://user-images.githubusercontent.com/3337501/168509501-aaa46929-b240-464a-923d-3900869a5700.png)

如图，在菜单中如何实现这样的显示

### 💻 示例代码 Sample code

是否可以在设置菜单那里，增加一个参数，是否 v-html 方法渲染 ，默认为false

**Comment by sendya** [comment]
菜单标题上控制，或者尝试 slot `menuItemRender`

**Comment by lilei03** [comment]
> 

你好，我在文档里没有找到关于菜单标题栏和 menuItemRender slot 的描述，能给个链接吗？

> 菜单标题上控制，或者尝试 slot `menuItemRender`
