### ISSUE TITLE
[Feature] 1.x 版本想增加 Menu 的 click 事件

### ISSUE THREAD

**Issue by bluescurry** [vueComponent/pro-layout#231]
### 🥰 需求描述 Description of Requirement

业务需求需要在点击侧边栏的当前路由菜单时重新刷新该路由页面。因下周一要上线，麻烦看到能尽快回复下，非常感谢~

### 🧐 解决方案 Solution

当前使用的是该库 1.x 的版本，能否在 src/components/RouteMenu/BaseMenu.jsx 的 dynamicProps 里增加一个 click 事件 emit 出来。

### 🚑 其他信息 Other information

如果作者您没时间的话，我可以提个PR，不过得麻烦您告诉下要基于那个分支拉代码，我没找到1.x的版本分支。。。

**Comment by myangle1120** [comment]
+1，我们也有这样的需求

**Comment by sendya** [comment]
https://github.com/vueComponent/pro-components/tree/v2

**Comment by bluescurry** [comment]
> https://github.com/vueComponent/pro-components/tree/v2

麻烦审下代码吧，https://github.com/vueComponent/pro-components/pull/233

**Comment by sendya** [comment]
@ant-design-vue/pro-layout@1.0.13
