### ISSUE TITLE
引入暗色模式，菜单栏不生效问题，是我哪里写错了么

### ISSUE THREAD

**Issue by liuge19910224** [vueComponent/pro-layout#238]
![image](https://user-images.githubusercontent.com/23229579/180350458-fc6d91c1-4e4b-46e7-b65d-09bc491c8e5c.png)
![image](https://user-images.githubusercontent.com/23229579/180350501-76f01119-dd3b-4fe5-9e39-c18cbb3c974e.png)

**Comment by liuge19910224** [comment]
只有中间一部分生效了

**Comment by liuge19910224** [comment]
![image](https://user-images.githubusercontent.com/23229579/180351197-9d0af40f-5b74-435f-bd18-96b92f45cda8.png)

**Comment by sendya** [comment]
mix 模式应该是暂不支持的，有 top, side 可以使用

**Comment by liuge19910224** [comment]
嗯嗯好的

**Comment by sendya** [comment]
升级 @ant-design-vue/pro-layout@3.2.3

**Comment by YTT-TTY** [comment]
> mix 模式应该是暂不支持的

@ant-design-vue/pro-layout@3.2.3 mix 模式是不是也不支持？

**Comment by luocong2016** [comment]
"ant-design-vue": "3.3.0-beta.4",
  "@ant-design-vue/pro-layout": "^3.2.3"
  
  mix 还是左侧菜单还是不存在
