### ISSUE TITLE
[BUG] layout是top时，切换到二级菜单，刷新页面后二级菜单会弹出一直显示

### ISSUE THREAD

**Issue by yushushu122** [vueComponent/pro-layout#248]
### 🐛 Bug 描述 Bug description

layout是top时，切换到二级菜单，刷新页面后二级菜单会弹出一直显示

### 🏞 期望结果 Desired result

不显示

### 🚑 其他信息 Other information

<img width="462" alt="截屏2022-10-06 21 07 29" src="https://user-images.githubusercontent.com/9691688/194320924-9b5d2609-91ef-447f-9b59-a95600a7c37f.png">

**Comment by sendya** [comment]
看下是不是手动设置了 openKeys
