### ISSUE TITLE
PageHeaderProps 的值是 undefined 导致使用 jsx 时无法设置 extra 属性

### ISSUE THREAD

**Issue by shawbena** [vueComponent/pro-layout#25]
https://github.com/vueComponent/pro-layout/blob/f6f01f09a236f51eab4d49b89b98ef29dc27ba7a/src/components/PageHeaderWrapper/index.jsx#L8

**Comment by shawbena** [comment]
suggest:
const {props} = PageHeader
or:
export PagHeaderProps in PageHeader

**Comment by sendya** [comment]
update [@ant-design-vue/pro-layout@0.3.8](https://www.npmjs.com/package/@ant-design-vue/pro-layout)
