### ISSUE TITLE
不使用国际化时settingDrawer显示异常

### ISSUE THREAD

**Issue by Kaworus** [vueComponent/pro-layout#26]
问题描述：prolayout中的i18nRender设置为false后，prolayout中的settingdrawer组件，显示的名字异常。
![image](https://user-images.githubusercontent.com/36876417/89846447-dd7ff180-dbb3-11ea-91fa-853d20859af5.png)
![image](https://user-images.githubusercontent.com/36876417/89846544-16b86180-dbb4-11ea-99d2-344810a1ee2e.png)
期望结果：可否通过传参的方式，在关闭i18n后，显示指定语言的文字呢。

**Comment by sendya** [comment]
请自行传递 i18nRender 给 SettingDrawer
