### ISSUE TITLE
能否更新下编译依赖，node11太低了

### ISSUE THREAD

**Issue by zxiaozhou** [vueComponent/pro-layout#28]
能否更新下编译最低node要求，11太低了。。下载网站找了大半天也没找到11版本。。

**Comment by sendya** [comment]
打包出来后的依赖库，不受版本影响

**Comment by zxiaozhou** [comment]
> 打包出来后的依赖库，不受版本影响
我编译都过不了，，mac只能下载到12，，11下载都成问题

**Comment by zxiaozhou** [comment]
> 打包出来后的依赖库，不受版本影响

既然都独立出来了，，还是希望提供友好的二次开发的能力。

**Comment by zxiaozhou** [comment]
@sendya 或者提供下解决办法我自行处理。。。mac找了大半天11找不到，brew也安装不了11

**Comment by sendya** [comment]
欢迎 PR

**Comment by sendya** [comment]
https://nodejs.org/dist/v11.15.0/

**Comment by zxiaozhou** [comment]
@sendya 已提pr，目前已经支持到v14.7.0

**Comment by zxiaozhou** [comment]
@sendya 我是用brew管理的，，官网直接下载找了大半天没找到brew也没法下载就放弃了

**Comment by zxiaozhou** [comment]
@sendya vs-tools更新了编译没问题，，但发现引入有问题，，是查什么环境吗？启动ant-design-vue-pro后页面打不开
![image](https://user-images.githubusercontent.com/62740686/89977314-6a52aa00-dc9d-11ea-81d0-2daa536b9731.png)
