### ISSUE TITLE
[BUG] Modal关闭时闪烁

### ISSUE THREAD

**Issue by MisakaTAT** [vueComponent/pro-layout#284]
### 🐛 Bug 描述 Bug description

```json
"dependencies": {
  "@ant-design-vue/pro-layout": "^3.2.4",
  "ant-design-vue": "^3.2.20"
}
```
在使用 `pro-layout` 的情况下，`Modal` 组件关闭时会闪烁，但是[文档](https://antdv.com/components/modal-cn)内的示例是正常的。

https://github.com/vueComponent/pro-components/assets/32693466/656fb4e9-187b-4a72-86f3-e16a23f1949c

### 🏞 期望结果 Desired result

正常关闭

### 🚑 其他信息 Other information

参考信息
https://github.com/ant-design/ant-design/issues/39013
https://github.com/ant-design/ant-design/issues/39054

**Comment by MisakaTAT** [comment]
已解决，该问题是 [preview-pro](https://github.com/sendya/preview-pro) App.vue 中的 css 样式导致，非 pro-layout bug。

**Comment by donghero** [comment]
> 已解决，该问题是 [preview-pro](https://github.com/sendya/preview-pro) App.vue 中的 css 样式导致，非 pro-layout bug。

补充一下"@ant-design-vue/pro-layout": "^3.2.4", 这里的APP.vue 也有相关样式 
`.zoom-enter-active,
.zoom-leave-active {
  animation-duration: 0.3s;
  animation-fill-mode: both;
  animation-name: zoomIn;
}

.zoom-leave-active {
  animation-direction: reverse;
}


`

可以去掉
