### ISSUE TITLE
how can i set default openkeys

### ISSUE THREAD

**Issue by oneyouzi** [vueComponent/pro-layout#30]
just about the title,i want to know where i can set it

**Comment by sendya** [comment]
which title ?

**Comment by oneyouzi** [comment]
> which title ?

i want the right menu to open by default,where set it?

**Comment by sendya** [comment]
The menu does not have a default openKeys, only be opened through the current route

**Comment by Anima-No** [comment]
没有默认全部打开吗？openKeys
