### ISSUE TITLE
vue.config.js publicPath配置不为"/"时。defaultSettings.js的primaryColor设置失效

### ISSUE THREAD

**Issue by Fallsleep** [vueComponent/pro-layout#33]
[[主题颜色错误]主题相关覆盖错误问题集中反馈](https://github.com/vueComponent/ant-design-vue-pro/issues/284#issuecomment-628361154) 中有人提过这个问题和解决方式，不过使用`pro-layout`时没法修改相关代码。

希望能针对该问题做一定的修正。

**Comment by jackytse** [comment]
遇到同样问题了，changeUrl 方法里路径写死了，似乎没办法修改

**Comment by zss1004504439** [comment]
我是这样解决的 publicPath 和 outputDir 改为一致
`
  publicPath: '/admin/',
  outputDir: 'admin',
`
`
fileName: '../admin/css/theme-colors-[contenthash:8].css',
`
求更好的方法！！！
