### ISSUE TITLE
如何设置可以让左边的menu默认hide掉

### ISSUE THREAD

**Issue by Kimi1020** [vueComponent/pro-layout#34]
就是左边的sidermenu完全hide掉， collapsed只能折叠sidemenu。
有没有可能让menu完全隐藏掉，然后只显示最上面的icon，点击icon出现menu的抽屉？

看了ant design vue的源代码， 怎么把collapsedWidth 传给Sider？

是否可以在SiderMenu.jsx 里面提供collapsedWidth  传给Sider？

谢谢

**Comment by sendya** [comment]
siderWidth = 0
