### ISSUE TITLE
menu 是不是还不支持 disabled属性

### ISSUE THREAD

**Issue by zhangmrit** [vueComponent/pro-layout#35]
我这边碰到一个人，有这种需求，正常也不会有，看了源码好像没看到支持的地方，原组件支持

**Comment by sendya** [comment]
可以考虑 menuRender 自己来渲染菜单

**Comment by zhangmrit** [comment]
> 可以考虑 menuRender 自己来渲染菜单

自己渲染实现了，发布私包总归不是那么方便

**Comment by sendya** [comment]
menuRender 是 slot，怎么会跟发私包啥关系？
