### ISSUE TITLE
我该怎么启动这个项目或者运行这个库

### ISSUE THREAD

**Issue by TomatoDroid** [vueComponent/pro-layout#39]
<img width="1321" alt="WX20200918-081340@2x" src="https://user-images.githubusercontent.com/22388686/93540668-fb94fa80-f986-11ea-85e6-3566d121413d.png">

**Comment by TomatoDroid** [comment]
node 的版本为14.7

**Comment by sendya** [comment]
```bash
cd examples
npm i
npm run serve
```
