### ISSUE TITLE
新版 next 分支的 examples 如何运行

### ISSUE THREAD

**Issue by tomgao365** [vueComponent/pro-layout#43]
请问 [next](https://github.com/vueComponent/pro-layout/tree/next) 分支的 examples 代码如何跑起来？是使用了什么cli工具么？`vue serve` 貌似不支持 tsx

**Comment by sendya** [comment]
看 package.json

**Comment by tomgao365** [comment]
`npm start` 启动报错，less配置未开启 `javascriptEnabled: true`
```bash
ERROR in ./src/GridContent/GridContent.less
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/less-loader/dist/cjs.js):


// https://github.com/ant-design/ant-motion/issues/44
.bezierEasingMixin();
^
Inline JavaScript is not enabled. Is it set in your options?
```

**Comment by eth3lbert** [comment]
@tomgao365 
因爲 vc-tools@3.0.0 還沒有支援自定 loaderOptions

目前可行解決方式:
1. yarn install `'https://github.com/vueComponent/tools.git#master'`
2. 更改 package.json 中的 config 成
```
  "config": {
    "port": 9528,
    "entry": {
      "@ant-design-vue/pro-layout": [
        "./index.tsx"
      ]
    },
    "css":{
      "loaderOptions": {
        "less": { 
          "javascriptEnabled": true
        }
      }
    }
  },
```
p.s. 這裡使用 `yarn` 舉例，如用 `npm` 請自行轉換對應安裝方式
這樣應該就可以跑起來了

**Comment by tomgao365** [comment]
@eth3lbert Thank you. 谢谢提醒，😀我直接改 `node_modules` 先跑起来了。不过你提供的方法更好，不用担心升级覆盖掉。
