### ISSUE TITLE
想了解 pro-layout 3.0 的一些计划安排和开发进度

### ISSUE THREAD

**Issue by tomgao365** [vueComponent/pro-layout#44]
公司最近计划现有多个项目使用 `vue3` 重构，新项目直接使用 `vue3` 开发，完全使用了[ant-design-vue](https://github.com/vueComponent/ant-design-vue)和[pro-layout](https://github.com/vueComponent/pro-layout)。由于业务限制，fork 使用了 `pro-layout` 修改增加一些业务化的东西，目前 `vue3` 版[pro-layout](https://github.com/vueComponent/pro-layout/tree/next)还在重构中，所以想了解一下新版开发计划安排。

不知新版的 `pro-layout` 仅是对现有版本的ts重构，还是计划增加一些新的特性，比如 [layout(react)](https://procomponents.ant.design/components/layout)一些调整：
1.菜单的宽度和头部的高度，使布局更紧凑
2.菜单的收起和展开放在了菜单最下方
这种调整在小分辨率笔记本下效果更好。

**Comment by sendya** [comment]
https://github.com/vueComponent/ant-design-vue-pro/issues/982
