### ISSUE TITLE
我如何才能给左边菜单栏增加徽标

### ISSUE THREAD

**Issue by thekingofvampire** [vueComponent/pro-layout#47]
看了文档，没找到怎么给左侧菜单栏增加徽标数，请指教

**Comment by sendya** [comment]
https://github.com/vueComponent/pro-layout/blob/master/examples/src/layouts/BasicLayout.vue#L13-L17


自己渲染

**Comment by thekingofvampire** [comment]
欧克  谢谢  文档没看到有这个参数🤣🤣

**Comment by thekingofvampire** [comment]
> https://github.com/vueComponent/pro-layout/blob/master/examples/src/layouts/BasicLayout.vue#L13-L17
> 
> 自己渲染

还有一个问题  目前使用pro-layout  右侧内容除顶部外的数据展示区域如何设置页面内滚动，而不是整个document滑动呢

**Comment by sendya** [comment]
css 给你要滚动的元素设置 overflow

**Comment by thekingofvampire** [comment]
> css 给你要滚动的元素设置 overflow

哦尅 了解了  谢谢啦

**Comment by lany1721** [comment]
> https://github.com/vueComponent/pro-layout/blob/master/examples/src/layouts/BasicLayout.vue#L13-L17
> 
> 自己渲染

你好，headerContentRender 和 headerRender 都不生效，请问应该选择哪个属性进行渲染

**Comment by lany1721** [comment]
.知道原因了。yarn自动安装的包是0.3.2版本，升级后就有效了

**Comment by zss1004504439** [comment]
`/src/components/RouteMenu/BaseMenu.jsx` `renderSubMenu` 增加个 `renderCount`
<a-badge count={meta.count} />
