### ISSUE TITLE
收起侧边栏时侧边栏宽度设置

### ISSUE THREAD

**Issue by shanghaihehework** [vueComponent/pro-layout#50]
![image](https://user-images.githubusercontent.com/73152165/96974149-679cec80-154b-11eb-9e3b-bc2f2aaaae24.png)
当侧边栏收起时，侧边栏宽度位为80px。 没有找到设置的参数，是否设计如此，还是我没找到

**Comment by sendya** [comment]
设计如此

**Comment by shanghaihehework** [comment]
理解不了 啊。 这个为什么没开出啦 。又要被老板骂了

**Comment by sendya** [comment]
规范设计上就是 80px，一直如此， demo 亦同。 从未表明目前的版本支持修改宽度
