### ISSUE TITLE
如何控制不渲染 footer

### ISSUE THREAD

**Issue by shanghaihehework** [vueComponent/pro-layout#51]
没有找到不渲染footer的方法

**Comment by oracle87** [comment]
遇到同样的问题，查看源码应该没有设置项。只能v-slot:footerRender下添加一个空的标签如：<span></span>去除掉默认的显示，但是问题是下方多了48px（footer）的高度。

**Comment by chenxianfei** [comment]
我强制把他隐藏掉了

**Comment by Pengjee** [comment]
`
<template v-slot:footerRender>
     <div></div>
</template>
`
然后padding设置为0，或者直接display:node
`
.ant-layout-footer {
	display: none !important;
}
`

**Comment by sendya** [comment]
升级到
@ant-design-vue/pro-layout 1.0.4 pro-layout 属性 footerRender = false
