### ISSUE TITLE
请教下菜单能否匹配带参数的 URL？

### ISSUE THREAD

**Issue by 285858315** [vueComponent/pro-layout#52]
比如：
/page?group=0d124178-ea30-4b3a-a81e-3e34148527c9

https://github.com/vueComponent/pro-layout/blob/master/src/components/RouteMenu/BaseMenu.jsx#L131
这里的 selectedKeys 通过 $route.fullPath 获取是否可行？

**Comment by sendya** [comment]
你可以试试看 ，我没试过

**Comment by sendya** [comment]
pro-layout@next 应该有支持，需要自行进行逻辑处理
