### ISSUE TITLE
nuxt.js集成pro-layout运行报错

### ISSUE THREAD

**Issue by Gyang18** [vueComponent/pro-layout#57]
# nuxt编译环境

客户端+服务端渲染（client + ssr ）

# 错误重现步骤

1. 在plugins目录下引入
2. 在nuxt.config.js中引入
3. 设置为ssr渲染

![image](https://user-images.githubusercontent.com/24975063/98207074-0ecf4a00-1f76-11eb-8613-e855a294ca7d.png)

![image](https://user-images.githubusercontent.com/24975063/98207101-1e4e9300-1f76-11eb-9772-36531ace00f3.png)

# 报错如下：

![image](https://user-images.githubusercontent.com/24975063/98207192-44743300-1f76-11eb-9810-7702f367c2e2.png)

是该组件不支持ssr还是需要在nuxt中进行特殊的设置呢?

**Comment by sendya** [comment]
没试过，按理说应该可以，欢迎提供解决方案

**Comment by ye21st** [comment]
> # nuxt编译环境
> 客户端+服务端渲染（client + ssr ）
> 
> # 错误重现步骤
> 1. 在plugins目录下引入
> 2. 在nuxt.config.js中引入
> 3. 设置为ssr渲染
> 
> ![image](https://user-images.githubusercontent.com/24975063/98207074-0ecf4a00-1f76-11eb-8613-e855a294ca7d.png)
> 
> ![image](https://user-images.githubusercontent.com/24975063/98207101-1e4e9300-1f76-11eb-9772-36531ace00f3.png)
> 
> # 报错如下：
> ![image](https://user-images.githubusercontent.com/24975063/98207192-44743300-1f76-11eb-9810-7702f367c2e2.png)
> 
> 是该组件不支持ssr还是需要在nuxt中进行特殊的设置呢?

请问您的问题解决了吗？

**Comment by Gyang18** [comment]
@ye21st 解决方案是暂时关闭了ssr渲染，我最近比较忙没有仔细研究该问题的解决方案

**Comment by Gyang18** [comment]
@sendya 好的，空了研究下

**Comment by BobSongCN** [comment]
我也在nuxt里碰到这个问题。无法解决。是因为less加载不出来导致的

**Comment by yuanfang-dev** [comment]
问题解决了吗？
