### ISSUE TITLE
pageHeaderWrapper无法配置sub-title

### ISSUE THREAD

**Issue by NiShuiXingZ** [vueComponent/pro-layout#58]
查看代码发现pageHeaderWrapper未预留sub-title配置项，只能重写pageHeaderRender，请问是否可以添加sub-title属性
![问题](https://user-images.githubusercontent.com/4465323/98217621-b43dea00-1f85-11eb-856d-0dee23e76dbe.jpg)
？

**Comment by oracle87** [comment]
![问题](https://user-images.githubusercontent.com/4465323/98217737-db94b700-1f85-11eb-87d6-131bcbe06f93.jpg)

**Comment by sendya** [comment]
老版本没有 sub-title 的需求，所以没写

**Comment by sendya** [comment]
欢迎 PR

**Comment by NiShuiXingZ** [comment]
> 欢迎 PR

好的，已提交
