### ISSUE TITLE
prolayout配置菜单方式

### ISSUE THREAD

**Issue by RyanChent** [vueComponent/pro-layout#59]
请问prolayout是否有菜单的slot可以更改呢，默认的菜单和需求不太匹配，目前只找到侧边菜单可以改的地方，顶部菜单好像没法改，menu不传就报错，有较好的方式保留用prolayout的情况下改变菜单的响应方式吗

**Comment by sendya** [comment]
#46

**Comment by RyanChent** [comment]
感谢回复，这边已拉取源码自行修改a-sub-menu弹出方式完毕

**Comment by haoyanhong** [comment]
> 感谢回复，这边已拉取原始代码自行修改a-sub-menu点击方式完成

您好，请问您这个问题是怎么解决的，我现在也有这样的需求

**Comment by RyanChent** [comment]
你拉取这个pro-layout的src下来改，然后basicLayout那里引用你改完的这个组件，主要是改
![image](https://user-images.githubusercontent.com/26846090/100494114-5d3cc680-3179-11eb-93b2-3eb2204b256c.png)
画红的这个，jsx看不习惯，我改成模板语法了，然后自己建立二级菜单引入，因为是公司项目，不好发出来，具体的不懂也可以私聊我看看，不过自己写的话，就需要处理权限那些和hidden:true的路由不显示这些

**Comment by RyanChent** [comment]
> > 感谢回复，这边已拉取原始代码自行修改a-sub-menu点击方式完成
> 
> 您好，请问您这个问题是怎么解决的，我现在也有这样的需求

你拉取这个pro-layout的src下来改，然后basicLayout那里引用你改完的这个组件，主要是改
image
画红的这个，jsx看不习惯，我改成模板语法了，然后自己建立二级菜单引入，因为是公司项目，不好发出来，具体的不懂也可以私聊我看看，不过自己写的话，就需要处理权限那些和hidden:true的路由不显示这些

**Comment by RyanChent** [comment]
> > 感谢回复，这边已拉取原始代码自行修改a-sub-menu点击方式完成
> 
> 您好，请问您这个问题是怎么解决的，我现在也有这样的需求

https://github.com/vueComponent/pro-layout/issues/59#issuecomment-735040236

**Comment by RyanChent** [comment]
> > 感谢回复，这边已拉取原始代码自行修改a-sub-menu点击方式完成
> 
> 您好，请问您这个问题是怎么解决的，我现在也有这样的需求

![image](https://user-images.githubusercontent.com/26846090/100494142-c290b780-3179-11eb-84a8-ac59d19a5850.png)
改成这样的响应方式

**Comment by haoyanhong** [comment]
> > > 感谢回复，这边已拉取原始代码自行修改a-sub-menu点击方式完成
> > 
> > 
> > 您好，请问您这个问题是怎么解决的，我现在也有这样的需求
> 
> ![image](https://user-images.githubusercontent.com/26846090/100494142-c290b780-3179-11eb-84a8-ac59d19a5850.png)
> 改成这样的响应方式
怎么可以私聊呢？

**Comment by RyanChent** [comment]
qq: 846296072，备注的时候说一下antdpro就好




------------------&nbsp;Original&nbsp;------------------

**Comment by haoyanhong** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "vueComponent/pro-layout"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月28日(星期六) 中午1:15
收件人:&nbsp;"vueComponent/pro-layout"<pro-layout@noreply.github.com&gt;;
抄送:&nbsp;"凉心@"<2624265785@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [vueComponent/pro-layout] prolayout配置菜单方式 (#59)





 qq: 846296072，备注的时候说一下antdpro就好 
 
 
 
 
 ------------------&amp;nbsp;Original&amp;nbsp;------------------
