### ISSUE TITLE
page-header-wrapper内的tabs属性问题

### ISSUE THREAD

**Issue by shouwangshe** [vueComponent/pro-layout#61]
`<page-header-wrapper

    :tabProps="tabProps"

    :tabList="tabList"

    :tab-change="tabChange"

    :title="false"

    content="表单页用于向用户收集或验证信息，基础表单常见于数据项较少的表单场景。">
</>
tabProps: {
     type: 'card',
      size: 'large'
 }`
可否这样使用？
tabList和tab-change是可用的。我的需求是如下：
![image](https://user-images.githubusercontent.com/26875279/98791256-c0bbba00-243f-11eb-9278-254153e5b3e2.png)

![image](https://user-images.githubusercontent.com/26875279/98791191-a255be80-243f-11eb-9053-09793772df95.png)
如果不能使用，可否增加加强tabs的配置。
图片不知道为啥打不开，可以打开链接，是可以看到的。

**Comment by sendya** [comment]
欢迎PR
