### ISSUE TITLE
innertia.js 使用pro-layout 报错

### ISSUE THREAD

**Issue by 957651480** [vueComponent/pro-layout#68]
使用的是laravel-mix+inertia.js 构建单页应用，引入pro-layout 报如下错误，laravel-mix 包含了webpack4

app.js:153841 [Vue warn]: Error in render: "TypeError: Cannot read property 'theme' of undefined"

found in

---> <SettingDrawer>
       <ALocaleProvider>
         <LocaleReceiver>
           <AConfigProvider>
             <Anonymous>
               <ALayoutContent>
                 <WrapContent>
                   <Anonymous>
                     <ALayout>
                       <Anonymous>
                         <ALayout>
                           <VueContainerQuery>
                             <ProConfigProvider>
                               <BasicLayout> at resources/js/Layouts/Ant.vue
                                 <Dashboard> at resources/js/Pages/Dashboard.vue
                                   <Inertia>
                                     <Root>

**Comment by sendya** [comment]
本项目目前仅支持 Vue 以及 Vue-CLI 环境或 Webpack4 环境，其他环境由于精力有限，无法支持，你可以尝试兼容或更换其他库
