### ISSUE TITLE
vue3.0中[Vue warn]: Invalid prop: type check failed for prop "openKeys". Expected Array, got Undefined

### ISSUE THREAD

**Issue by poetwolf** [vueComponent/pro-layout#69]
[Vue warn]: Invalid prop: type check failed for prop "openKeys". Expected Array, got Undefined  
  at <BaseMenu onUpdate:openKeys=fn<onUpdateOpenKeys> onUpdate:selectedKeys=fn<onUpdateSelectedKeys> menus=undefined  ... > 
  at <ALayoutSider class="ant-pro-sider ant-pro-sider-dark ant-pro-sider-undefined" width=undefined breakpoint=undefined  ... > 
  at <SiderMenu prefixCls="ant-pro" isChildrenLayout=false fixSiderbar=false  ... > 
  at <SiderMenuWrapper prefixCls="ant-pro" isChildrenLayout=false fixSiderbar=false  ... > 
  at <Anonymous prefixCls="ant-layout" hasSider=undefined tagName="section"  ... > 
  at <ProProvider i18n=fn<defaultI18nRender> > 

vue3.0中提示如上所示的警告，请问怎么解决呢？谢谢！

**Comment by sendya** [comment]
**prop "openKeys". Expected Array, got Undefined**
