### ISSUE TITLE
内部引用组件报错

### ISSUE THREAD

**Issue by huhaha24** [vueComponent/pro-layout#71]
使用pro-layout组件时，会报这个错误，大家碰到过吗
[Vue warn]: Invalid handler for event "change": got undefined
found in
---> <VueContainerQuery>
           <ProConfigProvider>
             <BasicLayout> at src/layouts/BasicLayout.vue

**Comment by l2m2** [comment]
同问

**Comment by l2m2** [comment]
添加`:handleMediaQuery="handleMediaQuery"`后没有报错。
