### ISSUE TITLE
page-header-wrapper可以自定义面包屑吗

### ISSUE THREAD

**Issue by herosPan** [vueComponent/pro-layout#74]
想去掉面包屑跳转，一级菜单必须有重定向，否则点击会出现空白页

**Comment by sendya** [comment]
`v-slot:breadcrumbRender`

另外，为什么一级菜单不设置默认重定向？

**Comment by herosPan** [comment]
> `v-slot:breadcrumbRender`
> 
> 另外，为什么一级菜单不设置默认重定向？

设置默认重定向某菜单后，若无此菜单权限再跳转会出现无权限的情况  感觉体验可能不是很好
