### ISSUE TITLE
headerRender 没有渲染出来

### ISSUE THREAD

**Issue by chenxianfei** [vueComponent/pro-layout#78]
<template>
  <pro-layout
    :siderWidth="siderWidth"
    :menus="menus"
    :collapsed="collapsed"
    :mediaQuery="query"
    :isMobile="isMobile"
    :handleMediaQuery="handleMediaQuery"
    :handleCollapse="handleCollapse"
    :i18nRender="i18nRender"
    v-bind="settings"
  >
    <template v-slot:headerRender> <div>这是头部</div> </template>

    <BasicBreadcrumb />
    
  </pro-layout>
</template>

headerRender 的插槽没有起作用

**Comment by sendya** [comment]
![image](https://user-images.githubusercontent.com/5404542/105199256-88d89d80-5b79-11eb-9cde-4847bc5fb51a.png)

headerRender 目前只能使用 props 传递 function，不支持 slot
