### ISSUE TITLE
自定义菜单图标

### ISSUE THREAD

**Issue by nnzbz** [vueComponent/pro-layout#79]
侧边栏的菜单图标只能用默认自带的，这远远不够，能不能支持自定义图标，至少能支持iconfont.com的项目图标库就好了

**Comment by sendya** [comment]
icon 可以传递 VNode 或 SVG 请自行渲染

**Comment by axetroy** [comment]
这有什么文档可以描述在哪里设置 icon 吗

**Comment by webxiaonew** [comment]
iconfont中的svg的可以，.png的img可以吗
