### ISSUE TITLE
关于动态生成菜单的问题

### ISSUE THREAD

**Issue by zhanghanbing1998** [vueComponent/pro-layout#82]
您好，我在使用antdv-pro时使用的是后端接口返回的菜单，但是当我点击菜单中的任何一个子菜单时，菜单会自动收起，刷新页面页面对应的菜单也不会自动处于展开状态，麻烦帮忙看下是什么原因？
[![svTMcj.gif](https://s3.ax1x.com/2021/01/27/svTMcj.gif)](https://imgchr.com/i/svTMcj)

**Comment by sendya** [comment]
path 对不上，看下是不是非绝对路径
