### ISSUE TITLE
如果直接用onCollapse, 会报onCollapse is not a function的错误

### ISSUE THREAD

**Issue by hoozi** [vueComponent/pro-layout#88]
在layout里直接用onCollapse 来接收collapse的状态会报这个错误
查了一下props 发现一个坑爹的问题，如下：
<img width="361" alt="QQ20210208-121035@2x" src="https://user-images.githubusercontent.com/2281961/107175042-c016cd80-6a06-11eb-82d0-4356316feb75.png">

也就是vue3 jsx props的合并，会把同名的函数合并成一个数组？所以是不是在源码的basiclayout里面 不能用{...props} 而是要omit 把onCollapse去掉之后， 再把props往下传递？

**Comment by sendya** [comment]
pro-layout 应该只提供了 emit 的事件监听

**Comment by hoozi** [comment]
> pro-layout 应该只提供了 emit 的事件监听

源码里和props里有onCollapse的方式
