### ISSUE TITLE
next: 我是否可以为pro-layout添加route或location属性以使menu响应路由变化

### ISSUE THREAD

**Issue by lihxhit** [vueComponent/pro-layout#92]
next分支： 现在的菜单栏并不能自动响应点击面包屑后的路由变化

**Comment by sendya** [comment]
你说的 `面包屑` 点击后的变化是哪些变化？
如果是路由发生改变，只需要使用者监听 route 变化，并更新 selectedKeys 即可。

可以在使用 pro-layout 的 layout 组件中 watch route，并按照自己的逻辑进行过滤赋值。
这个操作按目前的设计没必要由 BaseMenu 做。我希望的是 selectedKeys 受控
