### ISSUE TITLE
欢迎参与本项目功能讨论

### ISSUE THREAD

**Issue by sendya** [vueComponent/pro-layout#97]
目前讨论中的内容：
- [RouteContext] 有关全局都需要的状态控制讨论 #96

有新的想法可直接在 [pro-layout/discussions](https://github.com/vueComponent/pro-layout/discussions) 中创建

**Comment by liujiayii** [comment]
package.json的仓库url错误

**Comment by LengYXin** [comment]
这段代码太局限性了，除了 路由配置的 name 属性其他的都用不了。
就比如我配置菜单只想配置 path 并不想配置 name 那么这里就会出现 点击菜单没有反应的情况
https://github.com/vueComponent/pro-layout/blob/b56fb57998b5982a6b37c13485ff3ece9674ebe7/src/SiderMenu/BaseMenu.tsx#L163

如果不能完美使用 router-link 建议这里开放 slot 
还有一种方法就是这里使用属性声明的方法而不使用表达式。这样需要更改这个渲染函数的人可以直接改写prototype

**Comment by sendya** [comment]
@LengYXin 

有规划， 还没做
https://github.com/vueComponent/pro-layout/blob/b56fb57998b5982a6b37c13485ff3ece9674ebe7/src/BasicLayout.tsx#L239-L243

**Comment by LengYXin** [comment]
@sendya 看到了。还有个建议是可以充分的使用 provide / inject 做状态管理，虽然不是必须的，可读性会增加不少。其实也看个人习惯了。现在看到源码里面有比较臃肿的一级一级的 props ，RouteContext 中倒是使用了一些，不过和 basic 中的又冗余了

**Comment by sendya** [comment]
> @sendya 看到了。还有个建议是可以充分的使用 provide / inject 做状态管理，虽然不是必须的，可读性会增加不少。其实也看个人习惯了。现在看到源码里面有比较臃肿的一级一级的 props ，RouteContext 中倒是使用了一些，不过和 basic 中的又冗余了

来 pr？

**Comment by sendya** [comment]
传递 props 是为了里面的子组件可以独立引用执行。而且 props 有进行定义的话，明明比 provide inject 更明确这个组件需要什么

**Comment by sendya** [comment]
比如，开放 menuRender 时，可以直接引用 BaseMenu 并自己构建渲染数据。

**Comment by LengYXin** [comment]
> 传递 props 是为了里面的子组件可以独立引用执行。而且 props 有进行定义的话，明明比 provide inject 更明确这个组件需要什么

组件的单独使用 定义props是更明确，但是针对 BasicLayout 来说。会更好，props 和 provide 共存，让props优先级大于provide
不影响组件单独使用，把 BasicLayout 的props 定义顶层的 config 或者 给 RouteContext ，个人看法~ ~ 因为 一层一层往上找 传递的 props 真的很痛苦，还得担心中间有没有被串改。 【狗头保命】

**Comment by wulucxy** [comment]
@LengYXin 这个问题也看到了，强制传name 不太合理，目前只能自己实现了，beta 版本不太敢用

**Comment by sendya** [comment]
> @LengYXin 这个问题也看到了，强制传name 不太合理，目前只能自己实现了，beta 版本不太敢用

不太明白你说的强制传 name 是说的哪个

**Comment by LengYXin** [comment]
> > @LengYXin 这个问题也看到了，强制传name 不太合理，目前只能自己实现了，beta 版本不太敢用
> 
> 不太明白你说的强制传 name 是说的哪个

菜单的 vue router link 的配置。只有name 可用。现在我用 patch-package 自己打了个补丁。
![image](https://user-images.githubusercontent.com/19631404/121163453-5fe34b80-c881-11eb-88af-ac621d95f965.png)

**Comment by LengYXin** [comment]
@wulucxy 可以试试 patch-package 去打个补丁。然后没发现其他问题了。

**Comment by wulucxy** [comment]
@LengYXin 打算自己写一个，自定义的场景比较多，目测无法满足
